config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  root :to => redirect('/restaurants')

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

  resources :users

  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  belongs_to :user
  has_many :reviews

  validates :user, presence: true

  mount_uploader :image, RestaurantPictureUploader

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    if current_user
      @restaurant = Restaurant.new
    else
      redirect_to '/'
    end
  end

  # GET /restaurants/1/edit
  def edit
    redirect_to '/' unless current_user && current_user.id == set_restaurant.user_id
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant && current_user
        current_user.restaurants << @restaurant
        @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    if current_user.id == set_restaurant.user_id
      @restaurant.destroy
      respond_to do |format|
        format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to '/'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :image, :phone_number, :address)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h2>Listing Restaurants</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id='restaurants'>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= image_tag(restaurant.image, width: '100') %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <% if current_user && current_user.id == restaurant.user_id %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Delete', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  <%= link_to 'New Restaurant', new_restaurant_path %>
<% end %>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@restaurant.image, width: '50%') %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<% if @restaurant.reviews.length > 0 %>
  <h3>Reviews</h3>
  <ul>
    <li><% @restaurant.reviews.each do |review| %>
      <p><%= review.description %></p>
      <p>Rating: <%= review.rating %></p>
    </li>
  <% end %>
  </ul>
<% end %>

<% if current_user && current_user.id != @restaurant.user_id %>
  <%= link_to 'New Review', (new_review_path.to_s + '?restaurant_id=' + @restaurant.id.to_s) %> |
<% end %>

<% if current_user && current_user.id == @restaurant.user_id %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<% end %>
<%= link_to 'Back', restaurants_path %>