config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  root :to => redirect('/restaurants')

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

  resources :users

  resources :restaurants

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  ERRORS = {
    not_logged_in: 'You must be logged in to add a review.',
    own_restaurant: 'You cannot review your own restaurant.'
  }

  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    redirect_to '/'
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @restaurant = Restaurant.find_by_id(params[:restaurant_id])
    redirect_to '/', error: ERRORS[:not_logged_in] and return unless current_user

    redirect_to '/' and return unless @restaurant

    existing_review = @restaurant.reviews.find_by(user_id: current_user.id)
    redirect_to "/reviews/#{existing_review.id}", notice: 'You\'ve already posted a review!' and return if existing_review

    redirect_to '/', error: ERRORS[:own_restaurant] and return if current_user == @restaurant.user

    @review = Review.new(restaurant_id: params[:restaurant_id])
  end

  # GET /reviews/1/edit
  def edit
    # p params
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if !!@review && current_user
        current_user.reviews << @review
        @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:description, :rating, :restaurant_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :restaurant_id %>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/new.html.erb
<h2>New Review</h2>
<h3><%= @restaurant.name %></h3>

<%= render 'form' %>

<%= link_to 'Back', "/restaurants/#{@restaurant.id}" %>

app/views/reviews/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Delete', @review, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', "/restaurants/#{@review.restaurant_id}" %>